- id: forge-snapshot
  name: "forge snapshot"
  entry: run-forge-snapshot.sh
  files: '\.sol$'
  pass_filenames: false
  language: "script"
  require_serial: true
  description: "Runs `forge snapshot`"
