- id: forge-test
  name: run forge tests
  language: system
  entry: forge test
  files: ".sol$"
  pass_filenames: false
- id: forge-snapshot
  name: take forge snapshot
  language: script
  entry: run-forge-snapshot.sh
  always_run: true
  stages: [post-commit]
